[colors.primary]
background = '#1a1a1a'
foreground = '#eeeeee'

[colors.normal]
black   = '#303536'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#778899'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

[colors.bright]
black   = '#434a4c'
red     = '#ee8b86'
green   = '#b7c37f'
yellow  = '#dfb777'
blue    = '#66ccff'
magenta = '#dfa5b4'
cyan    = '#a1c49c'
white   = '#ebe1d0'

[font]
size = 15

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[terminal.shell]
program = "/usr/bin/fish"

[window]
opacity = 0.9

[window.padding]
x = 20
y = 20
