#!/bin/bash
alacritty -e "./.config/sway/scripts/sway-file-search_exec" \
    -o window.dimensions.columns=20 \
    -o window.dimensions.lines=20 \
    -o font.size=16.0 \
    -o window.padding.x=20 \
    -o window.padding.y=20 \
    --title "fzf-switcher" \
    --hold
exit
