bindsym {
    $mod+Print exec grim -t png /home/$USER/Pictures/$(date +%Y-%m-%d_%H-%m-%s).png
    Print exec grim -t png -g "$(slurp)" /home/$USER/Pictures/$(date +%Y-%m-%d_%H-%m-%s).png
    $mod+Ctrl+v wf-recorder -f /home/$USER/Videos/$(date +%Y-%m-%d_%H-%m-%s).mp4
}
