# Layout stuff:
#
    bindsym $mod+b splith
    bindsym $mod+v splitv

    # bindsym $mod+s layout stacking
    # bindsym $mod+t layout tabbed
    # bindsym $mod+e layout toggle split
    bindsym $mod+w sticky toggle
    bindsym $mod+f fullscreen

    bindsym $mod+Shift+space floating toggle

    bindsym $mod+space focus mode_toggle

    # Move focus to the parent container
    bindsym $mod+a focus parent

    # Pop-up mode
    bindsym $mod+p sticky toggle
