
default_border none
hide_edge_borders smart
gaps outer 5
gaps inner 3

default_floating_border none

set $laptop 'AU Optronics 0x61ED Unknown'
bindswitch --reload --locked lid:on output $laptop disable
bindswitch --reload --locked lid:off output $laptop enable
